spring.application.name=order-service

# Server ? different port from user-service
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/order_service_db
spring.datasource.username=postgres
spring.datasource.password=20030101
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# JWT ? must be same secret as user-service
jwt.secret=your-very-long-and-secure-base64-secret-key-here-minimum-256-bits
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

